config/routes.rb
Airpic::Application.routes.draw do
  devise_for :users

  root 'home#index'
  post '/order'=> 'orders#create'

  resources :payments
  resources :recipients
  resources :orders, only: [:create, :index]
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  validates_presence_of :nickname, :name, :address_line1, :city, :state, :zip
  belongs_to :user

  @lob = Lob(api_key: ENV['LOB_API_KEY'])
  
  def self.save_lob_id_in_db(recipient_id, lob_id)
    r = Recipient.find(recipient_id)
    r.lob_id = lob_id
    r.save
  end

  def self.save_address_to_lob(recipient_from_web)
    r = { country: 'US' } #lob.addresses.create requires :country
    recipient_from_web.each_pair do |x, y|
      r.merge!(x.to_sym => y)
    end
    addy = @lob.addresses.create(r)
    addy["id"]
  end

  def self.delete_address_from_lob(lob_id)
    if lob_id
      @lob.addresses.destroy(lob_id)
    end
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  def new
    @recipient = Recipient.new
  end

  def index
    @address_book = current_user.recipients
  end

  def create
    @recipient = Recipient.new(recipient_params)
    @recipient.user = current_user

    if @recipient.save
      lob_id = Recipient.save_address_to_lob(params[:recipient])
      Recipient.save_lob_id_in_db(@recipient.id, lob_id)
      flash[:success] = "Address saved!"
      redirect_to recipients_path
    else
      flash[:alert] = "There was a problem saving the address."
      redirect_to new_recipient_path
    end
  end

  def edit
    @address_to_edit = Recipient.find(params[:id])
  end

  def update
    recipient = Recipient.find(params[:id])
    recipient.update_attributes(recipient_params)
    recipient.save
    redirect_to recipients_path
  end

  def destroy
    recipient = Recipient.find(params[:id])
    Recipient.delete_address_from_lob(recipient.lob_id)
    recipient.destroy
    redirect_to recipients_path
  end


  private

  def recipient_params
    params.require(:recipient).permit(:nickname, :name, :address_line1, :address_line2, :city, :state, :zip, :user_id)
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/edit.html.erb
<div align="center">

<h1>Edit <%= @address_to_edit.name.split[0] %>'s Address</h1>

<%= form_for @address_to_edit, url: { action: "update" } do |a| %>
	<p><%= a.text_field :nickname, value: @address_to_edit.nickname %></p>
	<p><%= a.text_field :name, value: @address_to_edit.name %></p>
	<p><%= a.text_field :address_line1, value: @address_to_edit.address_line1 %></p>
	<p><%= a.text_field :address_line2, value: @address_to_edit.address_line2 %></p>
	<p><%= a.text_field :city, value: @address_to_edit.city %></p>
	<p><%= a.text_field :state, value: @address_to_edit.state %></p>
	<p><%= a.text_field :zip, value: @address_to_edit.zip %></p>
	<p><%= a.submit 'Save Address' %>
<% end %>


</div> 

app/views/recipients/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5"><h1>Address Book</h1></div>
    <div class="col-md-4"><span class="pull-right">
    	<%= link_to 'New Address', new_recipient_path, class: 'btn btn-lg btn-primary', role: 'button' %>
    </span></div>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Full Name</th>
        <th>SMS Nickname</th>
        <th>Address</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
			<% @address_book.each do |a| %>
        <tr>
        	<td><%= @address_book.index(a) + 1 %></td>
          <td><%= a.name %></td>
          <td><%= a.nickname %></td>
          <td><%= "#{a.address_line1} #{a.address_line2}" %></td>
          <td><%= a.city %></td>
          <td><%= link_to 'Edit', edit_recipient_path(a.id) %></td>
          <td><%= link_to 'Delete', a, method: :delete, 
          				data: { confirm: "Are you sure you want to delete #{a.name}?" } %></td>
        </tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/recipients/new.html.erb
<div align="center">

<h1>New Address</h1>

<%= form_for :recipient, url: recipients_path, method: :post do |a| %>
	<p><%= a.text_field :nickname, :placeholder => 'nick' %></p>
	<p><%= a.text_field :name, :placeholder => 'Nick McDonnough' %></p>
	<p><%= a.text_field :address_line1, :placeholder => '2520 Elmont Dr' %></p>
	<p><%= a.text_field :address_line2, :placeholder => 'Apt 220A' %></p>
	<p><%= a.text_field :city, :placeholder => 'Austin' %></p>
	<p><%= a.text_field :state, :placeholder => 'TX' %></p>
	<p><%= a.text_field :zip, :placeholder => '78741' %></p>
	<p><%= a.submit 'Save Address' %>
<% end %>


</div> 