config/routes.rb
Airpic::Application.routes.draw do
  devise_for :users

  root 'home#index'
  post '/order'=> 'orders#create'

  resources :payments
  resources :recipients
  resources :orders, only: [:create, :index]
end

app/views/layouts/_link_suggestion.html.erb
<% if current_user.stamp_collection < 1 %>
	<hr><p>Uh oh. You don't have any stamps! Please remember to purchase stamps <%= link_to 'here', new_payment_path %> in order to send postcards.</p><hr>
<% end %>

<% if current_user.recipients.size < 1 %>
	<hr><p>You don't have anyone in your address book!  Without a saved addresses you will not be able to send postcards.  Please click <%= link_to 'here', recipients_path %> to add someone.</p><hr>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_nav_sidebar.html.erb
<style type="text/css">
/*
 * Sidebar
 */

/* Hide for mobile, show later */
.sidebar {
  display: none;
}
@media (min-width: 768px) {
  .sidebar {
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    z-index: 1000;
    display: block;
    padding: 70px 20px 20px;
    background-color: #f5f5f5;
    border-right: 1px solid #eee;
  }
}

/* Sidebar navigation */
.nav-sidebar {
  margin-left: -20px;
  margin-right: -21px; /* 20px padding + 1px border */
  margin-bottom: 20px;
}
.nav-sidebar > li > a {
  padding-left: 20px;
  padding-right: 20px;
}
.nav-sidebar > .active > a {
  color: #fff;
  background-color: #428bca;
}
</style>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <br><br>
          <ul class="nav nav-sidebar">
          	<p class="navbar-text">Welcome, <%= current_user.first_name %>!<br />
          		Stamps: <u><strong><%= current_user.stamp_collection %></strong></u></p>
          </ul>
          <ul class="nav nav-sidebar">
            <li><%= link_to 'Past Orders', orders_path %></li>
            <li><%= link_to 'Address Book', recipients_path %></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><%= link_to 'Buy Stamps', payments_path %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          </ul>
        </div>

app/views/layouts/_nav_signed_in.html.erb
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to 'About', '#' %></li>
	<li><%= link_to 'Contact', 'javascript:contactAlert();' %></li>
	<li>|</li>
	<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
</ul>

app/views/layouts/_nav_signed_out.html.erb
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to 'About', '#' %></li>
	<li><%= link_to 'Contact', 'javascript:contactAlert();' %></li>
	<li>|</li>
	<li><%= link_to 'Sign up', new_user_registration_path %></li>
	<li><%= link_to 'Login', new_user_session_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airpic!</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
  <script src="https://checkout.stripe.com/v2/checkout.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<% if notice %>
  <p><%= notice %></p>
<% end %>
<% if alert %>
  <p><%= alert %></p>
<% end %>

<script> function contactAlert(){ alert('Please email nickmcd@gmail.com with questions.') } </script>
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
      <a class="navbar-brand" href="/">Airpic!</a>
    </div>

		<% if user_signed_in? %>
		  <%= render 'layouts/nav_signed_in' %>
		<% else %>
		  <%= render 'layouts/nav_signed_out' %>
		<% end %>

	</div>
</nav>

<% if user_signed_in? %>
	<%= render 'layouts/nav_sidebar' %>
	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<%= yield %>
	</div>
	</div></div><!-- end side nav -->
<% else %>
	<%= yield %>
<% end %>

</div>
</body>
</html>